import {
  Baby,
  Bike,
  Bolt,
  Archive,
  BookCheck,
  BookOpen,
  Box,
  Briefcase,
  BriefcaseBusiness,
  Building2,
  Bus,
  BusFront,
  CakeSlice,
  Calculator,
  CalendarDays,
  Camera,
  Car,
  CarFront,
  Caravan,
  Cat,
  ChefHat,
  CircleHelp,
  Clock,
  ClipboardList,
  Coffee,
  Cog,
  Construction,
  createLucideIcon,
  Dog,
  Drill,
  Droplets,
  Dumbbell,
  FileCheck,
  FileText,
  Flower2,
  Folder,
  FolderOpen,
  Folders,
  Gem,
  Glasses,
  GraduationCap,
  Hammer,
  HardHat,
  HeartPulse,
  Handshake,
  Headset,
  Hotel,
  House,
  Inbox,
  KeyRound,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  LockKeyhole,
  Luggage,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Monitor,
  Music,
  Notebook,
  Nut,
  Package,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Phone,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Scale,
  School,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  ShieldCheck,
  Smile,
  Smartphone,
  Sparkles,
  SprayCan,
  Sprout,
  Stethoscope,
  Store,
  Tag,
  Ticket,
  TreePine,
  Trophy,
  Tractor,
  Truck,
  Utensils,
  User,
  Users,
  WashingMachine,
  Watch,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const MopedIcon = createLucideIcon("Moped", [
  ["path", { d: "M4 17h2.2l2.6-5h3.2l2.4 3H18", key: "moped-body" }],
  ["path", { d: "M9 12l-1-3h3.5", key: "moped-seat" }],
  ["path", { d: "M13 12h3l2-4h2", key: "moped-handle" }],
  ["path", { d: "M17 8h3", key: "moped-grip" }],
  ["circle", { cx: "6", cy: "17", r: "2.5", key: "moped-back-wheel" }],
  ["circle", { cx: "18", cy: "17", r: "2.5", key: "moped-front-wheel" }],
]);

const ScooterIcon = createLucideIcon("Scooter", [
  ["path", { d: "M21 4h-3.5l2 11.05", key: "scooter-handle" }],
  ["path", { d: "M6.95 17h5.142c.523 0 .95-.406 1.063-.916a6.5 6.5 0 0 1 5.345-5.009", key: "scooter-deck" }],
  ["circle", { cx: "19.5", cy: "17.5", r: "2.5", key: "scooter-front-wheel" }],
  ["circle", { cx: "4.5", cy: "17.5", r: "2.5", key: "scooter-back-wheel" }],
]);

export const CATEGORY_ICON_KEYS = Object.freeze([
  "CAR",
  "BIKE",
  "MOPED",
  "TRUCK",
  "TRAILER",
  "TRACTOR",
  "SCOOTER",
  "BUS",
  "BUS_FRONT",
  "CAR_FRONT",
  "NUT",
  "BOLT",
  "WRENCH",
  "HAMMER",
  "DRILL",
  "PACKAGE",
  "BOX",
  "CART",
  "TAG",
  "BRIEFCASE",
  "BRIEFCASE_BUSINESS",
  "FOLDER",
  "FOLDER_OPEN",
  "FOLDERS",
  "CLIPBOARD_LIST",
  "CALENDAR_DAYS",
  "MESSAGE",
  "PHONE",
  "USER",
  "USERS",
  "MAIL",
  "INBOX",
  "FILE_CHECK",
  "NOTEBOOK",
  "ARCHIVE",
  "RECEIPT",
  "MEGAPHONE",
  "HANDSHAKE",
  "HEADSET",
  "CLOCK",
  "SHIELD_CHECK",
  "BOOK_CHECK",
  "COG",
  "LAYERS",
  "GRADUATION",
  "HEART",
  "SCISSORS",
  "UTENSILS",
  "LEAF",
  "SHIRT",
  "SPARKLES",
  "HELP",
  "COFFEE",
  "CHEF_HAT",
  "CAKE",
  "STORE",
  "SHOPPING_BAG",
  "PIZZA",
  "PAINTBRUSH",
  "DROPLETS",
  "SMILE",
  "STETHOSCOPE",
  "PILL",
  "GEM",
  "PAW",
  "DOG",
  "CAT",
  "HARD_HAT",
  "ZAP",
  "CONSTRUCTION",
  "WASHING_MACHINE",
  "SPRAY",
  "LAPTOP",
  "SMARTPHONE",
  "MONITOR",
  "GLASSES",
  "CALCULATOR",
  "SCALE",
  "LANDMARK",
  "FILE_TEXT",
  "BUILDING",
  "HOUSE",
  "KEY",
  "LOCK",
  "FLOWER",
  "TREE",
  "SPROUT",
  "DUMBBELL",
  "TROPHY",
  "WATCH",
  "MUSIC",
  "CAMERA",
  "PALETTE",
  "PARTY",
  "TICKET",
  "PLANE",
  "HOTEL",
  "MAP_PIN",
  "LUGGAGE",
  "BABY",
  "SCHOOL",
  "BOOK",
] as const);

export type CategoryIconKey = (typeof CATEGORY_ICON_KEYS)[number];

const CATEGORY_ICONS: Readonly<Record<CategoryIconKey, LucideIcon>> = Object.freeze({
  CAR: Car,
  BIKE: Bike,
  MOPED: MopedIcon,
  TRUCK: Truck,
  TRAILER: Caravan,
  TRACTOR: Tractor,
  SCOOTER: ScooterIcon,
  BUS: Bus,
  BUS_FRONT: BusFront,
  CAR_FRONT: CarFront,
  NUT: Nut,
  BOLT: Bolt,
  WRENCH: Wrench,
  HAMMER: Hammer,
  DRILL: Drill,
  PACKAGE: Package,
  BOX: Box,
  CART: ShoppingCart,
  TAG: Tag,
  BRIEFCASE: Briefcase,
  BRIEFCASE_BUSINESS: BriefcaseBusiness,
  FOLDER: Folder,
  FOLDER_OPEN: FolderOpen,
  FOLDERS: Folders,
  CLIPBOARD_LIST: ClipboardList,
  CALENDAR_DAYS: CalendarDays,
  MESSAGE: MessageCircle,
  PHONE: Phone,
  USER: User,
  USERS: Users,
  MAIL: Mail,
  INBOX: Inbox,
  FILE_CHECK: FileCheck,
  NOTEBOOK: Notebook,
  ARCHIVE: Archive,
  RECEIPT: Receipt,
  MEGAPHONE: Megaphone,
  HANDSHAKE: Handshake,
  HEADSET: Headset,
  CLOCK: Clock,
  SHIELD_CHECK: ShieldCheck,
  BOOK_CHECK: BookCheck,
  COG: Cog,
  LAYERS: Layers,
  GRADUATION: GraduationCap,
  HEART: HeartPulse,
  SCISSORS: Scissors,
  UTENSILS: Utensils,
  LEAF: Leaf,
  SHIRT: Shirt,
  SPARKLES: Sparkles,
  HELP: CircleHelp,
  COFFEE: Coffee,
  CHEF_HAT: ChefHat,
  CAKE: CakeSlice,
  STORE: Store,
  SHOPPING_BAG: ShoppingBag,
  PIZZA: Pizza,
  PAINTBRUSH: Paintbrush,
  DROPLETS: Droplets,
  SMILE: Smile,
  STETHOSCOPE: Stethoscope,
  PILL: Pill,
  GEM: Gem,
  PAW: PawPrint,
  DOG: Dog,
  CAT: Cat,
  HARD_HAT: HardHat,
  ZAP: Zap,
  CONSTRUCTION: Construction,
  WASHING_MACHINE: WashingMachine,
  SPRAY: SprayCan,
  LAPTOP: Laptop,
  SMARTPHONE: Smartphone,
  MONITOR: Monitor,
  GLASSES: Glasses,
  CALCULATOR: Calculator,
  SCALE: Scale,
  LANDMARK: Landmark,
  FILE_TEXT: FileText,
  BUILDING: Building2,
  HOUSE: House,
  KEY: KeyRound,
  LOCK: LockKeyhole,
  FLOWER: Flower2,
  TREE: TreePine,
  SPROUT: Sprout,
  DUMBBELL: Dumbbell,
  TROPHY: Trophy,
  WATCH: Watch,
  MUSIC: Music,
  CAMERA: Camera,
  PALETTE: Palette,
  PARTY: PartyPopper,
  TICKET: Ticket,
  PLANE: Plane,
  HOTEL: Hotel,
  MAP_PIN: MapPin,
  LUGGAGE: Luggage,
  BABY: Baby,
  SCHOOL: School,
  BOOK: BookOpen,
});

export const CATEGORY_ICON_FALLBACK = Tag;

export function resolveCategoryIcon(key: unknown): LucideIcon {
  if (typeof key !== "string") return CATEGORY_ICON_FALLBACK;
  return CATEGORY_ICONS[key.trim().toUpperCase() as CategoryIconKey] ?? CATEGORY_ICON_FALLBACK;
}
