import {
  Baby,
  Bike,
  Bolt,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  CakeSlice,
  Calculator,
  Camera,
  Car,
  Caravan,
  Cat,
  ChefHat,
  CircleDot,
  CircleHelp,
  Coffee,
  Cog,
  Construction,
  Dog,
  Drill,
  Droplets,
  Dumbbell,
  FileText,
  Flower2,
  Gem,
  Glasses,
  GraduationCap,
  Hammer,
  HardHat,
  HeartPulse,
  Hotel,
  House,
  KeyRound,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  LockKeyhole,
  Luggage,
  MapPin,
  Monitor,
  Music,
  Nut,
  Package,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Pill,
  Pizza,
  Plane,
  Scale,
  School,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Smartphone,
  Sparkles,
  SprayCan,
  Sprout,
  Stethoscope,
  Store,
  Tag,
  Ticket,
  TreePine,
  Trophy,
  Truck,
  Utensils,
  WashingMachine,
  Watch,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICON_KEYS = Object.freeze([
  "CAR",
  "BIKE",
  "MOPED",
  "TRUCK",
  "TRAILER",
  "NUT",
  "BOLT",
  "WRENCH",
  "HAMMER",
  "DRILL",
  "PACKAGE",
  "BOX",
  "CART",
  "TAG",
  "BRIEFCASE",
  "COG",
  "LAYERS",
  "GRADUATION",
  "HEART",
  "SCISSORS",
  "UTENSILS",
  "LEAF",
  "SHIRT",
  "SPARKLES",
  "HELP",
  "COFFEE",
  "CHEF_HAT",
  "CAKE",
  "STORE",
  "SHOPPING_BAG",
  "PIZZA",
  "PAINTBRUSH",
  "DROPLETS",
  "SMILE",
  "STETHOSCOPE",
  "PILL",
  "GEM",
  "PAW",
  "DOG",
  "CAT",
  "HARD_HAT",
  "ZAP",
  "CONSTRUCTION",
  "WASHING_MACHINE",
  "SPRAY",
  "LAPTOP",
  "SMARTPHONE",
  "MONITOR",
  "GLASSES",
  "CALCULATOR",
  "SCALE",
  "LANDMARK",
  "FILE_TEXT",
  "BUILDING",
  "HOUSE",
  "KEY",
  "LOCK",
  "FLOWER",
  "TREE",
  "SPROUT",
  "DUMBBELL",
  "TROPHY",
  "WATCH",
  "MUSIC",
  "CAMERA",
  "PALETTE",
  "PARTY",
  "TICKET",
  "PLANE",
  "HOTEL",
  "MAP_PIN",
  "LUGGAGE",
  "BABY",
  "SCHOOL",
  "BOOK",
] as const);

export type CategoryIconKey = (typeof CATEGORY_ICON_KEYS)[number];

const CATEGORY_ICONS: Readonly<Record<CategoryIconKey, LucideIcon>> = Object.freeze({
  CAR: Car,
  BIKE: Bike,
  MOPED: CircleDot,
  TRUCK: Truck,
  TRAILER: Caravan,
  NUT: Nut,
  BOLT: Bolt,
  WRENCH: Wrench,
  HAMMER: Hammer,
  DRILL: Drill,
  PACKAGE: Package,
  BOX: Box,
  CART: ShoppingCart,
  TAG: Tag,
  BRIEFCASE: Briefcase,
  COG: Cog,
  LAYERS: Layers,
  GRADUATION: GraduationCap,
  HEART: HeartPulse,
  SCISSORS: Scissors,
  UTENSILS: Utensils,
  LEAF: Leaf,
  SHIRT: Shirt,
  SPARKLES: Sparkles,
  HELP: CircleHelp,
  COFFEE: Coffee,
  CHEF_HAT: ChefHat,
  CAKE: CakeSlice,
  STORE: Store,
  SHOPPING_BAG: ShoppingBag,
  PIZZA: Pizza,
  PAINTBRUSH: Paintbrush,
  DROPLETS: Droplets,
  SMILE: Smile,
  STETHOSCOPE: Stethoscope,
  PILL: Pill,
  GEM: Gem,
  PAW: PawPrint,
  DOG: Dog,
  CAT: Cat,
  HARD_HAT: HardHat,
  ZAP: Zap,
  CONSTRUCTION: Construction,
  WASHING_MACHINE: WashingMachine,
  SPRAY: SprayCan,
  LAPTOP: Laptop,
  SMARTPHONE: Smartphone,
  MONITOR: Monitor,
  GLASSES: Glasses,
  CALCULATOR: Calculator,
  SCALE: Scale,
  LANDMARK: Landmark,
  FILE_TEXT: FileText,
  BUILDING: Building2,
  HOUSE: House,
  KEY: KeyRound,
  LOCK: LockKeyhole,
  FLOWER: Flower2,
  TREE: TreePine,
  SPROUT: Sprout,
  DUMBBELL: Dumbbell,
  TROPHY: Trophy,
  WATCH: Watch,
  MUSIC: Music,
  CAMERA: Camera,
  PALETTE: Palette,
  PARTY: PartyPopper,
  TICKET: Ticket,
  PLANE: Plane,
  HOTEL: Hotel,
  MAP_PIN: MapPin,
  LUGGAGE: Luggage,
  BABY: Baby,
  SCHOOL: School,
  BOOK: BookOpen,
});

export const CATEGORY_ICON_FALLBACK = Tag;

export function resolveCategoryIcon(key: unknown): LucideIcon {
  if (typeof key !== "string") return CATEGORY_ICON_FALLBACK;
  return CATEGORY_ICONS[key.trim().toUpperCase() as CategoryIconKey] ?? CATEGORY_ICON_FALLBACK;
}
